import { describe, expect, it } from "vitest";
import {
  convertSimplifiedToJapanese,
  buildJapaneseSurfaceFromZh,
  looksLikeAutoGeneratedSurface,
  applyZhSurfaceToTerm,
  type HonorificSurfaceTerm,
} from "./surfaceMapping";

describe("convertSimplifiedToJapanese", () => {
  it("converts simplified characters to Japanese kanji forms", () => {
    expect(convertSimplifiedToJapanese("图穆")).toBe("図穆");
    expect(convertSimplifiedToJapanese("怀少爷")).toBe("懐少爺");
    expect(convertSimplifiedToJapanese("陈统领")).toBe("陳統領");
    expect(convertSimplifiedToJapanese("赫连夫人")).toBe("赫連夫人");
  });
});

describe("buildJapaneseSurfaceFromZh", () => {
  it("maps Lord + 大人 to 卿", () => {
    expect(buildJapaneseSurfaceFromZh("Lord Tu Mu", "图穆大人")).toBe("図穆卿");
    expect(buildJapaneseSurfaceFromZh("Lord Huo Sang", "霍桑大人")).toBe("霍桑卿");
  });

  it("maps Commander + 统领 to 統領", () => {
    expect(buildJapaneseSurfaceFromZh("Commander Chen", "陈统领")).toBe("陳統領");
  });

  it("maps General + 将军 to 将軍", () => {
    expect(buildJapaneseSurfaceFromZh("General Huan", "桓将军")).toBe("桓将軍");
  });

  it("maps Young Master + 少爷 to 若様", () => {
    expect(buildJapaneseSurfaceFromZh("Young Master Huai", "怀少爷")).toBe("懐若様");
  });

  it("maps Lady + 夫人/小姐 appropriately", () => {
    expect(buildJapaneseSurfaceFromZh("Lady Helian", "赫连夫人")).toBe("赫連夫人");
    expect(buildJapaneseSurfaceFromZh("Lady Helian", "赫连小姐")).toBe("赫連嬢");
  });

  it("does not change non-title personal names", () => {
    expect(buildJapaneseSurfaceFromZh("Xiao Liu", "小六")).toBe("小六");
  });
});

describe("looksLikeAutoGeneratedSurface", () => {
  it("updates empty and dash surfaces", () => {
    expect(looksLikeAutoGeneratedSurface("Lord Tu Mu", "图穆大人", "")).toBe(true);
    expect(looksLikeAutoGeneratedSurface("Lord Tu Mu", "图穆大人", "-")).toBe(true);
  });

  it("updates old auto-generated 大人 surface", () => {
    expect(looksLikeAutoGeneratedSurface("Lord Tu Mu", "图穆大人", "図穆大人")).toBe(true);
  });

  it("treats new generated 卿 as auto-generated", () => {
    expect(looksLikeAutoGeneratedSurface("Lord Tu Mu", "图穆大人", "図穆卿")).toBe(true);
  });

  it("does not overwrite manual custom surface", () => {
    expect(looksLikeAutoGeneratedSurface("Lord Tu Mu", "图穆大人", "図穆さま")).toBe(false);
  });

  it("updates old Young Master 少爺 surface", () => {
    expect(looksLikeAutoGeneratedSurface("Young Master Huai", "怀少爷", "懐少爺")).toBe(true);
  });

  it("does not overwrite manual Young Master custom surface", () => {
    expect(looksLikeAutoGeneratedSurface("Young Master Huai", "怀少爷", "懐様")).toBe(false);
  });
});

describe("applyZhSurfaceToTerm", () => {
  it("fills empty Lord surface", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lord Tu Mu" },
      "图穆大人",
    );

    expect(result.zh_surface).toBe("图穆大人");
    expect(result.surface_ja).toBe("図穆卿");
    expect(result.confirmed_surface).toBe("図穆卿");
  });

  it("upgrades old auto-generated Lord surface", () => {
    const result = applyZhSurfaceToTerm(
      {
        source_text: "Lord Tu Mu",
        surface_ja: "図穆大人",
        confirmed_surface: "図穆大人",
      },
      "图穆大人",
    );

    expect(result.surface_ja).toBe("図穆卿");
    expect(result.confirmed_surface).toBe("図穆卿");
  });

  it("preserves manual surface", () => {
    const result = applyZhSurfaceToTerm(
      {
        source_text: "Lord Tu Mu",
        surface_ja: "図穆さま",
        confirmed_surface: "図穆さま",
      },
      "图穆大人",
    );

    expect(result.surface_ja).toBe("図穆さま");
    expect(result.confirmed_surface).toBe("図穆さま");
  });

  it("handles Commander Chen", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Commander Chen" },
      "陈统领",
    );

    expect(result.zh_surface).toBe("陈统领");
    expect(result.surface_ja).toBe("陳統領");
    expect(result.confirmed_surface).toBe("陳統領");
  });

  it("handles Xiao Liu", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Xiao Liu" },
      "小六",
    );

    expect(result.zh_surface).toBe("小六");
    expect(result.surface_ja).toBe("小六");
    expect(result.confirmed_surface).toBe("小六");
  });
});

describe("Episode 4 honorific mapping examples", () => {
  const cases = [
    ["Lord Tu Mu", "图穆大人", "図穆卿"],
    ["Lord Huo Sang", "霍桑大人", "霍桑卿"],
    ["Xiao Liu", "小六", "小六"],
    ["Commander Chen", "陈统领", "陳統領"],
  ] as const;

  it.each(cases)("%s + %s -> %s", (sourceText, zhSurface, expected) => {
    expect(buildJapaneseSurfaceFromZh(sourceText, zhSurface)).toBe(expected);

    const result = applyZhSurfaceToTerm({ source_text: sourceText }, zhSurface);
    expect(result.surface_ja).toBe(expected);
    expect(result.confirmed_surface).toBe(expected);
  });
});

describe("Episode 4 real data — applyZhSurfaceToTerm", () => {
  const ep4Cases = [
    ["Lord Tu Mu", "图穆大人", "図穆卿", "図穆卿"],
    ["Lord Huo Sang", "霍桑大人", "霍桑卿", "霍桑卿"],
    ["Xiao Liu", "小六", "小六", "小六"],
    ["Commander Chen", "陈统领", "陳統領", "陳統領"],
  ] as const;

  it.each(ep4Cases)("%s + %s → surface_ja=%s, confirmed=%s", (sourceText, zhSurface, expectedJa, expectedConfirmed) => {
    const result = applyZhSurfaceToTerm({ source_text: sourceText }, zhSurface);
    expect(result.zh_surface).toBe(zhSurface);
    expect(result.surface_ja).toBe(expectedJa);
    expect(result.confirmed_surface).toBe(expectedConfirmed);
  });
});

describe("Honorific regression examples", () => {
  const honorificCases = [
    ["Young Master Huai", "怀少爷", "懐若様", "懐若様"],
    ["Lady Helian", "赫连夫人", "赫連夫人", "赫連夫人"],
    ["Lady Helian", "赫连小姐", "赫連嬢", "赫連嬢"],
    ["General Huan", "桓将军", "桓将軍", "桓将軍"],
  ] as const;

  it.each(honorificCases)("%s + %s → surface_ja=%s", (sourceText, zhSurface, expectedJa, expectedConfirmed) => {
    const result = applyZhSurfaceToTerm({ source_text: sourceText }, zhSurface);
    expect(result.zh_surface).toBe(zhSurface);
    expect(result.surface_ja).toBe(expectedJa);
    expect(result.confirmed_surface).toBe(expectedConfirmed);
  });
});

describe("Edge cases — upgrade and preservation", () => {
  it("fills empty surface_ja and confirmed_surface", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lord Tu Mu" },
      "图穆大人",
    );
    expect(result.surface_ja).toBe("図穆卿");
    expect(result.confirmed_surface).toBe("図穆卿");
  });

  it("upgrades old 大人 surface to 卿", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lord Tu Mu", surface_ja: "図穆大人", confirmed_surface: "図穆大人" },
      "图穆大人",
    );
    expect(result.surface_ja).toBe("図穆卿");
    expect(result.confirmed_surface).toBe("図穆卿");
  });

  it("preserves manual custom surface_ja and confirmed_surface", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lord Tu Mu", surface_ja: "図穆さま", confirmed_surface: "図穆さま" },
      "图穆大人",
    );
    expect(result.surface_ja).toBe("図穆さま");
    expect(result.confirmed_surface).toBe("図穆さま");
  });

  it("preserves manual surface_ja but upgrades auto-generated confirmed_surface", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lord Tu Mu", surface_ja: "図穆さま", confirmed_surface: "図穆大人" },
      "图穆大人",
    );
    expect(result.surface_ja).toBe("図穆さま");
    expect(result.confirmed_surface).toBe("図穆卿");
  });

  it("upgrades old Young Master 少爺 surface to 若様", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Young Master Huai", surface_ja: "懐少爺", confirmed_surface: "懐少爺" },
      "怀少爷",
    );
    expect(result.surface_ja).toBe("懐若様");
    expect(result.confirmed_surface).toBe("懐若様");
  });

  it("preserves manual Young Master custom surface", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Young Master Huai", surface_ja: "懐様", confirmed_surface: "懐様" },
      "怀少爷",
    );
    expect(result.surface_ja).toBe("懐様");
    expect(result.confirmed_surface).toBe("懐様");
  });

  it("does not overwrite surface_ja when already a manual custom (Lady → 夫人)", () => {
    const result = applyZhSurfaceToTerm(
      { source_text: "Lady Helian", surface_ja: "へリアン夫人", confirmed_surface: "へリアン夫人" },
      "赫连夫人",
    );
    expect(result.surface_ja).toBe("へリアン夫人");
    expect(result.confirmed_surface).toBe("へリアン夫人");
  });
});

describe("selectedMap synthesis — Phase 3 loop simulation", () => {
  it("applies selectedMap.extracted values to Episode 4 terms", () => {
    const terms: HonorificSurfaceTerm[] = [
      { source_text: "Lord Tu Mu" },
      { source_text: "Lord Huo Sang" },
      { source_text: "Xiao Liu" },
      { source_text: "Commander Chen" },
    ];

    const selectedMap = new Map([
      ["Lord Tu Mu", { selected: "...", extracted: "图穆大人" }],
      ["Lord Huo Sang", { selected: "...", extracted: "霍桑大人" }],
      ["Xiao Liu", { selected: "...", extracted: "小六" }],
      ["Commander Chen", { selected: "...", extracted: "陈统领" }],
    ]);

    const updated = terms.map((term) => {
      const disambig = selectedMap.get(term.source_text);
      const extracted = disambig?.extracted;
      return extracted ? applyZhSurfaceToTerm(term, extracted) : term;
    });

    expect(updated[0].surface_ja).toBe("図穆卿");
    expect(updated[0].confirmed_surface).toBe("図穆卿");
    expect(updated[1].surface_ja).toBe("霍桑卿");
    expect(updated[1].confirmed_surface).toBe("霍桑卿");
    expect(updated[2].surface_ja).toBe("小六");
    expect(updated[2].confirmed_surface).toBe("小六");
    expect(updated[3].surface_ja).toBe("陳統領");
    expect(updated[3].confirmed_surface).toBe("陳統領");
  });

  it("skips terms not in selectedMap", () => {
    const terms: HonorificSurfaceTerm[] = [
      { source_text: "Lord Tu Mu" },
      { source_text: "Unknown Term" },
    ];

    const selectedMap = new Map([
      ["Lord Tu Mu", { selected: "...", extracted: "图穆大人" }],
    ]);

    const updated = terms.map((term) => {
      const disambig = selectedMap.get(term.source_text);
      const extracted = disambig?.extracted;
      return extracted ? applyZhSurfaceToTerm(term, extracted) : term;
    });

    expect(updated[0].surface_ja).toBe("図穆卿");
    expect(updated[1].surface_ja).toBeUndefined();
  });
});
